version: '3.5'
services:
  ssl_server:
   build:
     context: ./ssl_server/
   container_name: nginx
   depends_on:
     - web
     - varnish
     - redis_server
   volumes:
     - ./ssl_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
     - ./ssl_server/default:/etc/nginx/sites-enabled/default
     - ./ssl_server/nginx.conf:/etc/nginx/nginx.conf
   links:
     - web
     - varnish
     - redis_server
   ports:
     - "80:80"
     - "443:443"

  redis_server:
    build:
      context: ./redis_server/
    container_name: redis
    depends_on:
      - web
      - varnish
    volumes:
      - ./redis_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    links:
      - web

    ports:
      - "6379:6379"

  varnish:
    build:
      context: ./varnish/
    container_name: varnish
    depends_on:
      - web
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
      - ./varnish/varnish:/etc/default/varnish
      - ./varnish/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "6081:6081"
      - "6082:6082"
    links:
      - web

  web:
    build:
      context: ./apache2/
      args:
        TIMEZONE: ${TIMEZONE}
        LOCALES: ${LOCALES}
        LANGUAGE: ${LANGUAGE}
    container_name: apache2
    depends_on:
      - db
    volumes:
      - ./magento2:/var/www/html
      - ./apache2/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8080:8080"
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    container_name: phpmyadmin
    ports:
      - "8090:80"
    links:
      - db:db
  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    container_name: percona
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

volumes:
  dbdata:
