version: '3.5'
services:

  apache2:
    build:
      context: ./apache2/
      args:
        TIMEZONE: ${TIMEZONE}
        LOCALES: ${LOCALES}
        LANGUAGE: ${LANGUAGE}
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        GROUP_NAME: ${GROUP_NAME}
        GROUP_UID: ${GROUP_UID}
    container_name: apache2
    volumes:
      - ${MAGENTO_BASE_FOLDER}:/var/www/html
      - ./apache2/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./apache2/php.ini:/etc/php/7.2/apache2/conf.d/999-customphp.ini
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - magento-network

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - magento-network

  nginx:
   build:
     context: ./nginx/
   container_name: nginx
   depends_on:
     - apache2
     - varnish
     - redis
   volumes:
     - ./nginx/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
     - ./nginx/default:/etc/nginx/sites-enabled/default
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   ports:
     - "80:80"
     - "443:443"
     - "9001:9000"
   networks:
     - magento-network

  redis:
    build:
      context: ./redis/
    container_name: redis
    depends_on:
      - apache2
      - varnish
    volumes:
      - ./redis/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "6379:6379"
    networks:
      - magento-network

  varnish:
    build:
      context: ./varnish/
    container_name: varnish
    depends_on:
      - apache2
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
      - ./varnish/varnish:/etc/default/varnish
      - ./varnish/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "6081:6081"
      - "6082:6082"
    networks:
      - magento-network

  elasticsearch:
    image: elasticsearch:6.8.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - magento-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    container_name: phpmyadmin
    ports:
      - "8090:80"
    networks:
      - magento-network

networks:
  magento-network:
    driver: bridge

volumes:
  dbdata:
